/**
 * Route manifest
 *
 * TODO: it could be autogenerated based on the "pages" folder
 */
export const routes = {
  home: {
    href: "/",
  },
  account: {
    root: {
      href: "/account",
    },
    forgottenPassword: {
      href: "/account/forgotten-password",
    },
    resetPassword: {
      href: "/account/reset-password",
    },
    verifyEmail: {
      href: "/account/verify-email",
    },
    login: {
      href: "/account/login",
    },
    signup: {
      href: "/account/signup",
    },
    profile: {
      href: "/account/profile",
    },
  },
  vn: {
    admin: {
      home: {
        href: "/vn/admin",
      },
      crud: {
        href: "/vn/admin/crud",
      },
    },
  },
};
